import type { Booking, Notification, Task, TeamMember } from "./types";

export const team: TeamMember[] = [
  { id: "aryan", name: "Aryan", role: "Admin · Event Manager", presence: "online", isCurrentUser: true, isAdmin: true, hue: 265 },
  { id: "rohan", name: "Rohan", role: "Operations Lead", presence: "online", hue: 30 },
  { id: "priya", name: "Priya", role: "Design & Content", presence: "online", hue: 330 },
  { id: "aman", name: "Aman", role: "Logistics Lead", presence: "offline", hue: 200 },
  { id: "sneha", name: "Sneha", role: "Client Relations", presence: "offline", hue: 150 },
  { id: "karan", name: "Karan", role: "Finance", presence: "offline", hue: 80 },
];

export const seedBookings: Booking[] = [
  {
    id: "b1",
    title: "Corporate Retreat",
    clientName: "Horizon Tech Solutions",
    clientType: "Corporate Client",
    contactPerson: "Rohan Sharma",
    phone: "+91 98765 43210",
    email: "rohit@horizontech.com",
    clientQuote: "Annual team retreat for 25 people. Looking for comfortable stay, good food and some team bonding activities.",
    eventType: "Corporate Retreat",
    date: "2026-09-09",
    timeStart: "10:00 AM",
    timeEnd: "06:00 PM",
    venueName: "The Grand Hotel",
    venueCity: "Delhi",
    venueAddress: "Connaught Place, New Delhi, Delhi 110001",
    hallType: "Conference Hall",
    hallCost: 250000,
    peopleCount: 25,
    budgetTotal: 250000,
    budgetSpent: 120000,
    specialDemands: [
      { icon: "🎈", label: "Balloon Decoration", subLabel: "Theme: Blue & White" },
      { icon: "🎭", label: "Stage Setup", subLabel: "Backdrop + LED Screen" },
      { icon: "🥂", label: "Welcome Drink", subLabel: "Non-Alcoholic" },
      { icon: "🎂", label: "Custom Cake", subLabel: "Company Logo" },
    ],
    extraActivities: [
      { icon: "🎤", label: "Live Singer", subLabel: "1 hour performance" },
      { icon: "🎙️", label: "Event Anchor", subLabel: "For hosting & engagement" },
    ],
    assignedTeamMemberIds: ["aryan", "rohan", "priya", "aman", "sneha"],
    status: "upcoming",
  },
  {
    id: "b2",
    title: "Product Launch",
    clientName: "Nova Media",
    clientType: "Media Client",
    contactPerson: "Kavya Nair",
    phone: "+91 91234 56780",
    email: "kavya@novamedia.in",
    clientQuote: "Sleek launch evening for our new app. Press, influencers and a live demo wall.",
    eventType: "Product Launch",
    date: "2026-09-12",
    timeStart: "09:00 AM",
    timeEnd: "01:00 PM",
    venueName: "The Park",
    venueCity: "Jaipur",
    venueAddress: "MI Road, Jaipur, Rajasthan 302001",
    hallType: "Banquet Hall",
    hallCost: 180000,
    peopleCount: 120,
    budgetTotal: 400000,
    budgetSpent: 90000,
    specialDemands: [
      { icon: "📺", label: "LED Demo Wall", subLabel: "12ft x 8ft" },
      { icon: "📸", label: "Press Corner", subLabel: "Branded backdrop" },
    ],
    extraActivities: [{ icon: "🎧", label: "DJ", subLabel: "After-party set" }],
    assignedTeamMemberIds: ["aryan", "priya", "karan"],
    status: "upcoming",
  },
  {
    id: "b3",
    title: "Annual Meet",
    clientName: "Bright Future Pvt. Ltd.",
    clientType: "Corporate Client",
    contactPerson: "Vikram Rao",
    phone: "+91 99887 66554",
    email: "vikram@brightfuture.co",
    eventType: "Annual Meet",
    date: "2026-09-20",
    timeStart: "11:00 AM",
    timeEnd: "05:00 PM",
    venueName: "Taj Palace",
    venueCity: "Mumbai",
    venueAddress: "Apollo Bunder, Colaba, Mumbai 400001",
    hallType: "Auditorium",
    hallCost: 320000,
    peopleCount: 300,
    budgetTotal: 650000,
    budgetSpent: 40000,
    specialDemands: [{ icon: "🏆", label: "Award Ceremony", subLabel: "Trophies + Stage" }],
    extraActivities: [{ icon: "🎤", label: "Anchor", subLabel: "Bilingual host" }],
    assignedTeamMemberIds: ["aryan", "rohan", "aman"],
    status: "upcoming",
  },
  {
    id: "b4",
    title: "Client Dinner",
    clientName: "Skyline Group",
    clientType: "Hospitality Client",
    contactPerson: "Neha Kapoor",
    phone: "+91 90000 12345",
    email: "neha@skyline.com",
    eventType: "Client Dinner",
    date: "2026-09-27",
    timeStart: "07:00 PM",
    timeEnd: "11:00 PM",
    venueName: "Rooftop 32",
    venueCity: "Bengaluru",
    venueAddress: "UB City, Vittal Mallya Rd, Bengaluru 560001",
    hallType: "Rooftop Lounge",
    hallCost: 90000,
    peopleCount: 40,
    budgetTotal: 150000,
    budgetSpent: 10000,
    specialDemands: [{ icon: "🕯️", label: "Candle-lit Setup", subLabel: "Warm ambience" }],
    extraActivities: [{ icon: "🎷", label: "Jazz Trio", subLabel: "2 hour set" }],
    assignedTeamMemberIds: ["sneha", "karan"],
    status: "upcoming",
  },
  {
    id: "b5",
    title: "Wedding Reception",
    clientName: "Mehra Family",
    clientType: "Private Client",
    contactPerson: "Arjun Mehra",
    phone: "+91 98111 22334",
    email: "arjun.mehra@gmail.com",
    eventType: "Wedding",
    date: "2026-08-22",
    timeStart: "06:00 PM",
    timeEnd: "12:00 AM",
    venueName: "Leela Palace",
    venueCity: "Udaipur",
    venueAddress: "Lake Pichola, Udaipur 313001",
    hallType: "Lawn + Banquet",
    hallCost: 500000,
    peopleCount: 450,
    budgetTotal: 1200000,
    budgetSpent: 1200000,
    specialDemands: [{ icon: "🌸", label: "Floral Mandap", subLabel: "White orchids" }],
    extraActivities: [{ icon: "🎆", label: "Fireworks", subLabel: "10 min show" }],
    assignedTeamMemberIds: ["aryan", "rohan", "priya", "aman", "sneha", "karan"],
    status: "completed",
  },
];

export const seedTasks: Task[] = [
  { id: "t1", bookingId: "b1", title: "Confirm venue with client", assigneeId: "rohan", dueDate: "2026-09-09", dueTime: "9:00 AM", priority: "High", done: false },
  { id: "t2", bookingId: "b1", title: "Arrange catering", assigneeId: "priya", dueDate: "2026-09-09", dueTime: "10:30 AM", priority: "High", done: false },
  { id: "t3", bookingId: "b1", title: "Send final itinerary", assigneeId: "aman", dueDate: "2026-09-09", dueTime: "12:00 PM", priority: "Medium", done: false },
  { id: "t4", bookingId: "b1", title: "Book transport", assigneeId: "sneha", dueDate: "2026-09-09", dueTime: "2:00 PM", priority: "Medium", done: false },
  { id: "t5", bookingId: "b2", title: "Finalise LED wall vendor", assigneeId: "aryan", dueDate: "2026-09-10", dueTime: "11:00 AM", priority: "High", done: false },
  { id: "t6", bookingId: "b2", title: "Share press invite list", assigneeId: "aryan", dueDate: "2026-09-11", dueTime: "4:00 PM", priority: "Medium", done: false },
  { id: "t7", bookingId: "b3", title: "Collect trophy designs", assigneeId: "priya", dueDate: "2026-09-15", dueTime: "1:00 PM", priority: "Low", done: false },
  { id: "t8", bookingId: "b4", title: "Confirm jazz trio", assigneeId: "aryan", dueDate: "2026-09-25", dueTime: "6:00 PM", priority: "Low", done: true },
];

export const seedNotifications: Notification[] = [
  { id: "n1", type: "booking_assigned", title: "New booking assigned", description: "Corporate Retreat has been assigned to you.", time: "2h ago", read: false },
  { id: "n2", type: "task_reminder", title: "Task reminder", description: "Arrange catering for Corporate Retreat.", time: "3h ago", read: false },
  { id: "n3", type: "client_message", title: "Client message", description: "Horizon Tech Solutions: “Please confirm the final headcount by Friday.”", time: "5h ago", read: false },
  { id: "n4", type: "team_update", title: "Team update", description: "Rohan updated the venue details.", time: "1d ago", read: true },
  { id: "n5", type: "event_completed", title: "Event completed", description: "Wedding Reception has been marked as done.", time: "2d ago", read: true },
];

export const extraActivityOptions = [
  { icon: "🎤", label: "Singer" },
  { icon: "🎙️", label: "Anchor" },
  { icon: "🎧", label: "DJ" },
  { icon: "📷", label: "Photographer" },
  { icon: "➕", label: "Other" },
];

export const eventTypes = ["Corporate Retreat", "Product Launch", "Annual Meet", "Client Dinner", "Wedding", "Birthday", "Conference", "Other"];

export const savedVenues = [
  { name: "The Grand Hotel", city: "Delhi", address: "Connaught Place, New Delhi, Delhi 110001" },
  { name: "The Park", city: "Jaipur", address: "MI Road, Jaipur, Rajasthan 302001" },
  { name: "Taj Palace", city: "Mumbai", address: "Apollo Bunder, Colaba, Mumbai 400001" },
  { name: "Rooftop 32", city: "Bengaluru", address: "UB City, Vittal Mallya Rd, Bengaluru 560001" },
  { name: "Leela Palace", city: "Udaipur", address: "Lake Pichola, Udaipur 313001" },
];
