/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as BookingNewRouteImport } from './routes/booking.new'
import { Route as DayDateRouteImport } from './routes/day.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingNewRoute = BookingNewRouteImport.update({
  id: '/booking/new',
  path: '/booking/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DayDateRoute = DayDateRouteImport.update({
  id: '/day/$date',
  path: '/day/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/new': typeof BookingNewRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/new': typeof BookingNewRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bookings': typeof BookingsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/booking/$id': typeof BookingIdRoute
  '/booking/new': typeof BookingNewRoute
  '/day/$date': typeof DayDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bookings'
    | '/home'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/booking/$id'
    | '/booking/new'
    | '/day/$date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bookings'
    | '/home'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/booking/$id'
    | '/booking/new'
    | '/day/$date'
  id:
    | '__root__'
    | '/'
    | '/bookings'
    | '/home'
    | '/login'
    | '/notifications'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/booking/$id'
    | '/booking/new'
    | '/day/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookingsRoute: typeof BookingsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  BookingIdRoute: typeof BookingIdRoute
  BookingNewRoute: typeof BookingNewRoute
  DayDateRoute: typeof DayDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/new': {
      id: '/booking/new'
      path: '/booking/new'
      fullPath: '/booking/new'
      preLoaderRoute: typeof BookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/day/$date': {
      id: '/day/$date'
      path: '/day/$date'
      fullPath: '/day/$date'
      preLoaderRoute: typeof DayDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookingsRoute: BookingsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  BookingIdRoute: BookingIdRoute,
  BookingNewRoute: BookingNewRoute,
  DayDateRoute: DayDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
